#!/usr/bin/with-contenv bash

certificates() {
    CA_NAME=${CA_NAME:-"kopano-selfsigned-ca"}
    CA_SUBJECT=${CA_SUBJECT:-"/C=XX/ST=Kopano/L=Kopano/O=Kopano/CN="}
    CA_CERT_SUBJECT=${CA_CERT_SUBJECT:-${CA_SUBJECT}${CA_NAME}}
    CA_CERT_FILE=${CA_CERT_FILE:-"/certs/${CA_NAME}/${CA_NAME}.crt"}
    CA_KEY_FILE=${CA_KEY_FILE:-"$(dirname "${CA_CERT_FILE}")/${CA_NAME}.key"}
    CREATE_CA=${CREATE_CA:-"TRUE"}

    certificates_create_certificate_authority() {
        if [ ! -f "${CA_CERT_FILE}" ] ; then

            print_debug "Certificates: Creating Self Signed Certificate Authority"
            mkdir -p "$(dirname "${CA_CERT_FILE}")"
            chown -R kopano:kopano "$(dirname "${CA_CERT_FILE}")"
            sudo -u kopano echo "000a" > "$(dirname "${CA_CERT_FILE}")/serial"
            sudo -u kopano touch "$(dirname "${CA_CERT_FILE}")/certindex"

            silent eval "openssl req \
                  -newkey rsa:4096 -keyout ${CA_KEY_FILE} \
                  -x509 -days 3650 -nodes -out ${CA_CERT_FILE} \
                  -subj \"${CA_CERT_SUBJECT}\""

            chown -R kopano:kopano "${CA_KEY_FILE}" "${CA_CERT_FILE}"

            sudo -u kopano cat > "$(dirname "${CA_CERT_FILE}")"/"${CA_NAME}".conf << EOF
            [ ca ]
            default_ca = $CA_NAME

            [ $CA_NAME ]
            unique_subject = no
            new_certs_dir = .
            certificate = ${CA_CERT_FILE}
            database = $(dirname "${CA_CERT_FILE}")/certindex
            private_key = ${CA_KEY_FILE}
            serial = $(dirname "${CA_CERT_FILE}")/serial
            default_days = 3650
            default_md = sha256
            policy = ${CA_NAME}_policy
            x509_extensions = ${CA_NAME}_extensions

            [ ${CA_NAME}_policy ]
            commonName = supplied
            stateOrProvinceName = supplied
            countryName = supplied
            emailAddress = optional
            organizationName = supplied
            organizationalUnitName = optional

            [ ${CA_NAME}_extensions ]
            basicConstraints = CA:false
            subjectKeyIdentifier = hash
            authorityKeyIdentifier = keyid:always
            keyUsage = digitalSignature,keyEncipherment
            extendedKeyUsage = serverAuth,clientAuth

            [ req ]
            default_bits = 2048
            string_mask = utf8only
            default_md = sha256
            x509_extensions = v3_ca

            [default_conf]
            ssl_conf = ssl_sect

            [ssl_sect]
            system_default = system_default_sect

            [system_default_sect]
            MinProtocol = TLSv1.1
            MaxProtocol = TLSv1.2
            CipherString = DEFAULT
EOF
        else
            print_debug "Certificates: CA Already Exists"
        fi
    }

    certificates_create_certificate() {
        if [ "$1" != "" ] ; then

            if var_true "$CREATE_CA" ; then
                if [ ! -f "${CA_CERT_FILE}" ] || [ ! -f "${CA_KEY_FILE}" ] ; then
                    print_debug "Certificates: No CA Found - Creating before generating certificates"
                    certificates_create_certificate_authority
                fi
            fi
            CERT_SUBJECT="${CA_SUBJECT}$(basename "${1%%.*}")"

            if var_true "$CREATE_CA" ; then
                if [ ! -f "${1%%.*}".key ] ; then
                    print_debug "Certificates: Creating Certificate: ${1}"
                    silent eval "openssl req \
                          -newkey rsa:2048 -keyout ${1%%.*}.key \
                          -nodes -out ${1%%.*}.csr \
                          -subj \"${CERT_SUBJECT}\" \
                          -addext \"subjectAltName = DNS:localhost\""
                    chown -R kopano:kopano "${1%%.*}".key "${1%%.*}".csr
                fi
            else
                if [ ! -f "${1%%.*}".key ] ; then
                    print_debug "Certificates: Creating Certificate: ${1}"
                    silent eval "openssl req \
                          -new -x509 -nodes -days 3650
                          -config /usr/lib/ssl/openssl.cnf
                          -out ${1%%.*}.crt \
                          -keyout ${1%%.*}.key"
                    chown -R kopano:kopano "${1%%.*}".key "${1%%.*}".crt
                fi
            fi

            if var_true "$CREATE_CA" ; then
                if [ ! -f "${1%%.*}".cert ] ; then
                    print_debug "Certificates: Signing Certificate: ${1}"
                    silent eval "openssl ca -batch -config $(dirname "${CA_CERT_FILE}")/${CA_NAME}.conf -notext -in ${1%%.*}.csr -out ${1%%.*}.crt"
                    chown -R kopano:kopano "${1%%.*}".crt
                    rm -rf "$(tail -n 1 "$(dirname "${CA_CERT_FILE}")"/certindex | awk '{print $3}')".pem
                    rm -rf "${1%%.*}".csr
                fi
            fi

            if [ -f "${1%%.*}".crt ] && [ -f "${1%%.*}".key ] ; then
                print_debug "Certificates: Merging Certificate and Key for: ${1}"
                sudo -u kopano cat "${1%%.*}".crt "${1%%.*}".key > "${1%%.*}".pem
                chown -R kopano:kopano "${1%%.*}".pem
            fi

            if [ ! -f "${SERVER_SSL_PUBLIC_PATH}""$(basename "${1%%.*}")"-public.pem ] ; then
                print_debug "Certificates: Creating Public Key for: ${1}"
                mkdir -p "${SERVER_SSL_PUBLIC_PATH}"
                chown -R kopano:kopano "${SERVER_SSL_PUBLIC_PATH}"
                silent openssl x509 -in "${1%%.*}".crt -out "${SERVER_SSL_PUBLIC_PATH}""$(basename "${1%%.*}")"-public.pem -pubkey
                chown -R kopano:kopano "${SERVER_SSL_PUBLIC_PATH}""$(basename "${1%%.*}")"-public.pem
            fi
        fi
    }

    certificates_check_permissions() {
        if sudo -u kopano [ ! -r "${1}" ] ; then
            print_debug "Certificates: Setting Read Permissions on ${1}"
            chmod 444 "${1}"
        fi
    }

    certificates_check_certificates() {
        print_debug "Certificates: Checking Existence of ${1}"
        if [ ! -f "${1}" ] ; then
                mkdir -p "$(dirname "${1}")"
                chown -R kopano:kopano "$(dirname "${1}")"
                certificates_create_certificate "${1}"
        fi
    }

    certificates_trust_ca() {
        if var_true "$CREATE_CA" ; then
            if [ -f "${CA_CERT_FILE}" ]; then
                if [ ! -L /usr/local/share/ca-certificates/"$(basename "${CA_CERT_FILE}")" ] ; then
                    print_debug "Certificates: Trusting CA ${CA_NAME}"
                    ln -sf "${CA_CERT_FILE}" /usr/local/share/ca-certificates/
                    silent dpkg-reconfigure ca-certificates
                fi
            fi
        fi
    }

    case "$1" in
        *)
            certificates_check_certificates "${1}"
            certificates_check_permissions "${1}"
            certificates_trust_ca
        ;;
    esac
}

configure_logging() {
    print_debug "Logging: Configuring"
    if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
        print_debug "Logging: Set to ${LOG_TYPE}"
        mkdir -p "${LOG_PATH}"
        sed -i -e "s#<LOG_LOCATION>#${LOG_PATH}#g" /etc/logrotate.d/kapi
    else
        rm -rf /etc/logrotate.d/kapi
    fi

    ### Translate Logging
    case "$LOG_LEVEL" in
        "NONE" | "none" | "disabled" | "0" )
            LOG_LEVEL=0
            LOG_FILE="/dev/null"
        ;;
        "CRITICAL" | "critical" | "crit" | "1" )
            LOG_LEVEL=1
            kapi_log_level="fatal"
        ;;
        "ERROR" | "error" | "err" | "2" )
            LOG_LEVEL=2
            kapi_log_level="error"
        ;;
        "WARN" | "warn" | "3" )
            LOG_LEVEL=3
            kapi_log_level="warn"
        ;;
        "NOTICE" | "notice" | "4" )
            LOG_LEVEL=4
            kapi_log_level="info"
        ;;
        "INFO" | "info" | "5" )
            LOG_LEVEL=5
            kapi_log_level="info"
        ;;
        "DEBUG" | "debug" | "6" )
            LOG_LEVEL=6
            kapi_log_level="debug"
        ;;
    esac

    truefalse_yesno LOG_TIMESTAMPS
}

configure_kapi() {
        print_notice "KAPI: Auto Configuring"

        case "${KAPI_KVS_DB_TYPE}" in
            "SQLITE3" | "SQLITE" | "sqlite" | "sqlite3" )
                print_debug "KAPI: Setting SQLite3 Data Type"
                mkdir -p "$(dirname "${KAPI_KVS_DB_SQLITE_FILE}")"
                kapi_kvs_db_driver="sqlite3"
                kapi_kvs_db_dsn=${KAPI_KVS_DB_SQLITE_FILE}
                print_debug "KAPI: ${kapi_kvs_db_driver} | DSN: ${kapi_kvs_db_dsn}"
            ;;
            "MYSQL" | "mysql" | "MARIADB" | "mariadb" )
                print_debug "KAPI: Setting MariaDB Data Type"
                kapi_kvs_db_driver="mysql"
                kapi_kvs_db_dsn="[${KAPI_KVS_DB_USER}[:${KAPI_KVS_DB_PASS}]@][protocol[(${KAPI_KVS_DB_HOST})]]/${KAPI_KVS_DB_NAME}[?param1=value1&...&paramN=valueN]" # Needs Work
                print_debug "KAPI: ${kapi_kvs_db_driver} | DSN: ${kapi_kvs_db_dsn}"
            ;;
        esac

        if [ ! -f "${KAPI_PUBS_SECRET_KEY_FILE}" ]; then
            print_debug "KAPI: No PUBS API Secret Key File - Generating"
            mkdir -p "$(dirname "${KAPI_PUBS_SECRET_KEY_FILE}")"
            silent openssl rand -out "${KAPI_PUBS_SECRET_KEY_FILE}" -hex 64
        fi

        if [ -n "${KAPI_PLUGINS}" ] ; then
            kapi_plugins=$(cat<<EOF
plugins = ${KAPI_PLUGINS}
EOF
            )

        kapi_oidc_server_identifier="oidc_issuer_identifier = ${SERVER_OIDC_IDENTIFIER}"
        fi

        truefalse_yesno KAPI_DISABLE_TLS_VALIDATION
        cat <<EOF > "${CONFIG_PATH}""${KAPI_CONFIG_FILE}"
# Custom Generated Kopano KAPI Server Configuration! Do not edit, instead set ENV Vars
# If you want to use your own configuration files set SETUP_TYPE=MANUAL when starting container
# Last Generated on $(date)

insecure = ${KAPI_DISABLE_TLS_VALIDATION}
listen = ${KAPI_LISTEN_HOST}:${KAPI_LISTEN_PORT}
log_level = ${kapi_log_level}
${kapi_oidc_server_identifier}
plugin_grapi_socket_path = ${SOCKET_GRAPI}
plugin_kvs_db_datasource = ${kapi_kvs_db_dsn}
plugin_kvs_db_drivername = ${kapi_kvs_db_driver}
plugin_kvs_db_migrations = ${KAPI_KVS_PATH_DB_MIGRATIONS}
plugin_pubs_secret_key = ${KAPI_PUBS_SECRET_KEY_FILE}
plugins_path = ${KAPI_PATH_PLUGINS}
${kapi_plugins}
EOF
}

parse_config() {
    if [ -f "${1}" ] ; then
        print_debug "Parsing Config ${1}"
        while IFS="" read -r line || [ -n "$line" ]
            do
            if [[ "${line}" == *" = "* ]] ; then
                name=$(echo "$line" | awk '{print $1}')
                value=$(echo "$line" | awk '{print $3}')
                export "$name"="$value"
            fi
        done < "${1}"
    else
        print_error "Tried to parse config ${1} but it doesn't exist!"
    fi
}


wait_for_server() {

    case "${1}" in
            "KONNECT" | "konnect" | "KONNECT_SOCKET_SERVER" )
                socket_server=${KONNECT_SOCKET_SERVER}
            ;;
    esac

    socket_server=${socket_server:-"${SOCKET_SERVER}"}

    case "${socket_server}" in
            "file://"* )
                print_notice "Checking to see if Kopano Server socket is avaialable"
                wait_for_socket "${socket_Server}"
            ;;
            "htt"* )
                print_notice "Checking to see if Kopano Server port is avaialable"
                kchost=$(echo "${socket_server}" | awk -F / '{print $3}' | awk -F : '{print $1}')
                kcport=$(echo "${socket_server}" | awk -F / '{print $3}' | awk -F : '{print $2}')
                wait_for_port "$kchost" "$kcport"
            ;;
    esac
}
